# Generated by Django 2.2.3 on 2019-07-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Bus_needed',
            field=models.CharField(choices=[(1, 'Yes'), (2, 'No')], default='', max_length=10),
        ),
    ]
